### ISSUE TITLE
Canvas Titles change on-hover

### ISSUE THREAD

**Issue by Wussie** [snezhig/obsidian-front-matter-title#106]
Great plugin! 

As of my current version of Obsidian at least (v1.1.16 on OSX); I'm having an issue when using the 'Canvas' name replacement. It's showing the correctly resolved names normally for embedded notes when just looking at the canvas; however when I hover over the title with my mouse- it reverts back to the file's title. This happens both for 'fully embedded' notes as well as for notes that were scoped to a heading or block.

Would be nice to see this fixed, this plugin is very helpful!

**Comment by snezhig** [comment]
Hi, it's not a bug.
It is made to let you know the original name of canvas. 
But I can think about settings to change the behavior.

**Comment by snezhig** [comment]
Feel free to reopen the issue or create a new one.

**Comment by amorette-practicumfit** [comment]
Awesome plugin, thank you! 

I'm noticing on Canvas that the title above the top left of the note is replaced as expected, and in the embedded view, if the Header option is turned on, that's correct as well. However, when I zoom out so that the note content is replaced with its title inside the box, it's then showing the filename instead of the title. Is that intended? Or if not, can it be fixed?
