### ISSUE TITLE
Resolving titles from frontmatter arrays includes trailed commas and requires explicit array notation

### ISSUE THREAD

**Issue by Wussie** [snezhig/obsidian-front-matter-title#107]
I'm using this to basically rely on using `alias`-like things for most of my files; trying to not encode useful information in the filenames themselves to avoid relying on hierarchy too much. With Obsidian's built-in search (Ctrl+O) this works really well, allowing me to put multiple aliases if needed, in a variety of notations.

For me- it seems to make sense to configure this plugin to use `alias` field (as a fallback, I put `title` as main source but I don't use it that much); but there's a few inconsistencies with how the plugin parses the field vs how Obsidian does it themselves to support their search:

- Trailing commas are included in the plugin (e.g. `alias: SomeTitle,` shows as `SomeTitle,` in places where the plugin replaces it, but as `SomeTitle` in Obsidian's native support).
- Multi-line specified arrays only work with explicit array notation in the plugin (e.g. 
```
alias: 
 some alias
 another alias
``` 

works OK in the built-in support; but with the plugin it now shows up as a concatenated string reading like `some alias another alias` even though it's configured to use 'first entry only'. I can resolve it by replacing the frontmatter with:

```
alias: [
 some alias
 another alias
]
```
Explicitly including the array brackets. Minor problem of course; but aesthetically I prefer foregoing the angled brackets.

**Comment by snezhig** [comment]
Hi!
I can see here only 3 types of aliases: https://help.obsidian.md/Linking+notes+and+files/Aliases
I have not known about this feature yet.
Yes, plugin did not supports commas, but I can try to add it.

**Comment by pm64** [comment]
The plot thickens...

Obsidian's new "Properties" feature adds a smart frontmatter editor, which provides significant convenience, at the price of a little flexibility.

For example, it's no longer possible (without some workaround hack) to use "alias" as a frontmatter key -- Obsidian now forces you to use "aliases", and forces the value to be represented as an array.

There are likely several reasons users like @Wussie and myself prefer to use "alias" to this plugin's default "title" key, but in most cases it's likely because Obsidian's quick switcher will match against an "alias" (now "aliases") value, whereas there's no way for the quick switcher (or any quick switcher replacement plugin) to match against "title".

So, in light of this new Obsidian functionality, it would be extremely helpful to update the "value must be string or numeric" requirement in "Common main template" settings such that array values are also permitted. When the value of the specified template path is an array, the plugin should use the value of the first element in the array as the title.

This would allow seamless integration with the Properties feature, resolve @Wussie's issue, and improve workflow substantially for many users :)

**Comment by snezhig** [comment]
It is in preview version 1.4.x? 
Has it some breaking changes?

**Comment by pm64** [comment]
There's only one possibly semi-breaking change that I was just investigating.

Here is the relevant release note:

![image](https://github.com/snezhig/obsidian-front-matter-title/assets/10715458/ae38b282-12cf-4929-8ca9-be5c7e28797a)

I believe, as a result, you may need to update your excellent recently-added API, already adopted by https://github.com/LostPaul/obsidian-folder-notes.

In your plugin, when the user uses the new Properties feature to specify an "aliases" value, then specifies "alias" as the common main template YAML path, the correct value is resolved and displayed as the document title.

However, this scenario might not be handled correctly at the level of your API. I say this because https://github.com/LostPaul/obsidian-folder-notes still displays the *actual* title as the folder note title -- whereas if a "normal" YAML key (like the default "title") is used, https://github.com/LostPaul/obsidian-folder-notes correctly displays the replacement title.

**Comment by pm64** [comment]
One thought I had would be for you to actually allow array values for the common main template. If the value is an array, then the value of the first element in the array will be used as the title. Then the user can just specify "aliases" as their common main template, and not involve Obsidian's "alias <-> aliases" magic.

**Comment by snezhig** [comment]
API just provides the way to use internal resolvers and does nothing by itself.
Also you can use array to templates. Use first value or all of them.  But my plugin can not detect that `Foo, Bar` is an array `['Foo', 'Bar']`. And it will be interpreted like a string.

**Comment by pm64** [comment]
Indeed. This does appear to be a bug in https://github.com/LostPaul/obsidian-folder-notes .. I'll open an issue there. Thanks!

**Comment by snezhig** [comment]
I'm waiting for 1.4.0 to be released to look for any breaking changes.

**Comment by snezhig** [comment]
I close this issue. Feel free to reopen if it is actual.
