### ISSUE TITLE
How to replace names displayed on left tree bar?

### ISSUE THREAD

**Issue by qazero** [snezhig/obsidian-front-matter-title#111]
I'm running Obsidian 1.2.7 and tried installing this plugin just now. When I add the following front-matter to my note it doesn't do anything in my file-tree on the left:

```yaml
title: 'test title using plugin'
```

If I understand correctly, the plugin allows for displaying the title or alias mentioned in the front-matter instead of the filename (to be displayed in the file tree on the left). Is my understanding correct?

Wondering if it is a bug or I'm doing something wrong... Apologies in advance if this is user error.

**Comment by snezhig** [comment]
Hi, do you use a community plugin for the file tree? My plugin support native plugins which are out of the box.

**Comment by qazero** [comment]
Nope I do not. But I do use the following plugins, not sure if it matters or not:

https://github.com/ozntel/file-explorer-note-count
https://github.com/turulix/obsidian-folder-index
https://github.com/LostPaul/obsidian-folder-notes

**Comment by snezhig** [comment]
Can you give me screenshot of plugin's options and example of file?

**Comment by L33tCh** [comment]
I see the same. It was working but I have since synchronised with Obsidian Git as well... I wonder if there's a line-ending issue, with Android being one of my synched devices?
In my screenshots here, you can see that I've enabled Tabs, Headers and Explorer titles but only the first 2 are updating:
![Screenshot 2023-05-10 095241](https://github.com/snezhig/obsidian-front-matter-title/assets/1831643/7910dba2-b0b6-489c-a2ab-64fcd1b48098)
![Screenshot 2023-05-10 095236](https://github.com/snezhig/obsidian-front-matter-title/assets/1831643/901fb810-8f50-46dc-8bf4-1a92fca7f52b)
![Screenshot 2023-05-10 095151](https://github.com/snezhig/obsidian-front-matter-title/assets/1831643/3ec62825-05a2-40fc-9fe6-3ed6677f3d1a)

**Comment by snezhig** [comment]
I see that you have an old version of plugin. Can you update it?

**Comment by snezhig** [comment]
Does it work now?

**Comment by L33tCh** [comment]
Yes, thank you, perfect after the version update. I assume that one of the merges prioritized the incorrect config file or something.
