### ISSUE TITLE
[Feature Request] Option to replace real name in link with title

### ISSUE THREAD

**Issue by gentlegiantJGC** [Snezhig/obsidian-front-matter-title#18]
When linking between files it would be nice if the front matter title was displayed instead of the real title like this plugin does with the file explorer and graph view.

I think this should just be a case of modifying the text displayed if the tag is in the front matter using a markdown post processor.

I don't know if this would be possible in the source or preview modes.

**Comment by gentlegiantJGC** [comment]
This could probably be cleaned up (my knowledge of javascript is limited but this works)
Feel free to use the code if you want to include it.

```js
import {Plugin, MarkdownPostProcessorContext, parseLinktext, TFile} from 'obsidian';


export default class TitlePlugin extends Plugin {
	async onload() {
		console.log("Loaded Title Mutator")
		this.registerMarkdownPostProcessor(this.pdf_mutator.bind(this));
	}

	onunload() {}

	async mutate_link(el: HTMLElement){
		let text = el.getAttr("data-href");
		// Parse the link object
		let linktext = parseLinktext(text)
		// Pull the path from the link
		let link_path: string = linktext.path;
		let link_sub_path: string = linktext.subpath;
		if (link_sub_path[0] === "#"){
			link_sub_path = link_sub_path.slice(1)
		}

		if ((link_sub_path ? `${link_path} > ${link_sub_path}` : link_path) != el.getText()){
			// If the text is different it was probably changed by an alias. Do nothing
			return
		}

		// Find the relative path for the short name
		let link_tfile: TFile | null = this.app.metadataCache.getFirstLinkpathDest(link_path, "");
		if (link_tfile === null){
			return
		}
		let cache = this.app.metadataCache.getFileCache(link_tfile);
		if (cache === null){
			return
		}
		let frontmatter = cache.frontmatter
		if (frontmatter === null){
			return
		}
		if (frontmatter.hasOwnProperty("title") && typeof frontmatter.title === "string"){
			text = frontmatter.title;
			if (link_sub_path.length){
				text = text + ` > ${link_sub_path}`
			}
			el.setText(text);
		}
	}

	async pdf_mutator(el: HTMLElement, ctx: MarkdownPostProcessorContext){
		// Update all links to point to the pdf
		let linkElements = el.querySelectorAll('a.internal-link');
		for(let i = 0; i < linkElements.length; i++) {
			await this.mutate_link(linkElements[i] as HTMLElement)
		}
	}
}
```

**Comment by Snezhig** [comment]
Hi, thank you for the feedback.
I will explore this. If it is possible and does not make side effects, like editing the original content, I will try to add this feature.

**Comment by Trikzon** [comment]
A temporary fix is to set the `Front matter title path` to `alias` so that Obsidian automatically suggests the title. However, this might have unintended side effects that I haven't encountered yet and should be dealt with properly by the plugin.

**Comment by Snezhig** [comment]
I have not spent time on this feature yet, but this request in my queue.

**Comment by Trikzon** [comment]
I'd like to add that I have changed my solution to this problem:

I've realized as I've been adding more and more files that I don't want some files to autocomplete when making links. So what I have started doing is having this plugin use the `title` metadata field for the displayed title and for files that I want to autocomplete I use the `alias` metadata field.

I also discovered that the YAML metadata block has a feature called "anchors" which works sort of like variables so I only have to define the title once:
```
---
title: &title 'Example Title'
aliases: [*title]
---
```

I hope that if this plugin does make it so that file titles can be autocompleted that I would be able to disable it. I like having control over what files are aliased and what ones aren't.

**Comment by Snezhig** [comment]
@huyz , @gentlegiantJGC , @Trikzon 
Hi, you can try beta version[ 2.2.0-beta](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/2.2.0-beta). It brings manager that replace alias of links. But be careful, because it changes file's content.

**Comment by Trikzon** [comment]
It's nice that it changes links to alias to their front matter title, but that honestly isn't very useful for me because I don't know what my notes' real names are.

A more useful implementation of this would allow the autocompletion of links as if it was an alias:
![image](https://user-images.githubusercontent.com/29845000/190929419-6de58892-5de4-4d4c-9622-8c5937371ebe.png)

![image](https://user-images.githubusercontent.com/29845000/190929427-23a944db-a7ae-4ff6-b583-909e83b54c3a.png)

**Comment by Trikzon** [comment]
After playing around with it more, I realize that it actually solves an earlier issue of mine: #37 

I would still like to see it show up in the alias autocomplete, but maybe I should create a different issue for that?

**Comment by Trikzon** [comment]
and now everytime that I open Obsidian with Front Matter Title enabled with "File Note Link" enabled Obsidian soft crashes and becomes unresponsive. I had to edit the `data.json` file manually to revert to a working state.

There's no logs in the console and I have Front Matter Title's debug toggle enabled.

**Comment by Snezhig** [comment]
Have you tried this feature with 0.16.+ version? It may be the reason of crushes.

About "autocomplete as it is an alias" I  will check it after 0.16.+ release, because there can be many breaking changes.

**Comment by Trikzon** [comment]
Yes, I forgot to mention I am using 0.16.2.
If no one else crashes using 0.15.x then don't worry about it.
I'm just not going to use this feature for now :)

**Comment by Snezhig** [comment]
I close this issue and we can create new after 0.16.0 release.
