### ISSUE TITLE
[Feature Request] Display Front Matter Title in the Quick Switcher

### ISSUE THREAD

**Issue by Trikzon** [Snezhig/obsidian-front-matter-title#25]
It would be great if this plugin would replace the note titles in the Quick Switcher just like it does in the file tree.

**Comment by Snezhig** [comment]
Hi. I'm not sure about this feature, but I will look at this.

**Comment by pat-richter** [comment]
I would like to see this, too (since I've also stumbled across something like this in https://github.com/Snezhig/obsidian-front-matter-title/issues/22 - seems like this might become a common issue).

Have a look at the video again. While this comma thing seems to be an Obsidian issue, it might showcase the usecase. I'm using Zettelkasten system, all my notes are names "YYYYMMDD.HHmmss" and these are shown in the quick switcher as default. It would be awesome if the default title there is the same as configured within the plugin (e.g. first `aliases` entry for me).

Kind regards

**Comment by Snezhig** [comment]
@Trikzon, @pat-richter you can try this feature using [1.6.0-beta](https://github.com/Snezhig/obsidian-front-matter-title/releases/tag/1.6.0-beta) or wait a bit more until actual release

**Comment by Snezhig** [comment]
I'm going to close this issue. Feel free to reopen it or create new if it is needed.

**Comment by Trikzon** [comment]
Apologies for not responding earlier. Just reinstalled the plugin and this works great. Thanks for updating it! 😄
