### ISSUE TITLE
Support Inline Title

### ISSUE THREAD

**Issue by freddyheppell** [snezhig/obsidian-front-matter-title#65]
Obsidian v1 added an "Inline Title" feature, which puts the title as if it's an H1 at the top of the note, which currently displays as the real file name. I've disabled it for now, but it would be nice if there was a way to configure it to use the front matter title, even if that made it non-editable.

**Comment by Snezhig** [comment]
@freddyheppell yes, I have noticed this, but I have not looked for the way to support it yet, but I will.

**Comment by firefoxic** [comment]
It is also very necessary to display the title (alias) instead of the file name on the canvas.

![image](https://user-images.githubusercontent.com/3382798/211877254-c50b4aa1-a036-45c6-a898-1d740886aef6.png)
![image](https://user-images.githubusercontent.com/3382798/211877534-35f9aa18-4bc8-498e-a7fd-0af55a7145ce.png)
![image](https://user-images.githubusercontent.com/3382798/211877648-3b5ed1c3-2bef-47f7-a230-ab2fe743dd4f.png)
